from __future__ import annotations

import csv
import json
from collections import Counter
from pathlib import Path

from app.exporters import DB_FIELDS, _sql_value
from app.models import PolicyRecord
from app.sources.ai_laws_education import Candidate, TrackerRow

REVIEW_FIELDS = [
    "classification",
    "issues",
    "review_flags",
    "review_disposition",
    "review_resolution_note",
    "source_state",
    "state_code",
    "source_identifier",
    "policy_identifier",
    "normalized_identifier_key",
    "source_year",
    "source_category",
    "category",
    "categories",
    "source_status",
    "status",
    "status_detail",
    "key_requirement",
    "summary",
    "title",
    "policy_type",
    "effective_date",
    "implementation_timeline",
    "source_url",
    "research_source_name",
    "research_source_url",
    "research_source_date",
    "status_as_of_date",
    "last_updated",
    "last_verified_at",
    "detail_last_action_date",
    "duplicate_existing_title",
    "duplicate_existing_source_url",
]

DUPLICATE_FIELDS = [
    "classification",
    "state_code",
    "policy_identifier",
    "normalized_identifier_key",
    "ai_laws_year",
    "existing_year_evidence",
    "existing_title",
    "existing_source_url",
    "existing_research_source_name",
    "existing_research_source_url",
    "ai_laws_research_source_url",
    "reason",
    "merge_recommendation",
]

CONFLICT_FIELDS = [
    "state_code",
    "policy_identifier",
    "source_year",
    "field",
    "existing_value",
    "ai_laws_value",
    "existing_research_source_name",
    "existing_research_source_url",
    "ai_laws_research_source_url",
    "resolution",
]

NORMALIZED_FIELDS = REVIEW_FIELDS


def write_csv(path: Path, rows: list[dict], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def write_raw_json(path: Path, rows: list[TrackerRow], fetch_log: list[dict]) -> None:
    payload = {
        "rows": [row.raw_dict() for row in rows],
        "detail_fetch": fetch_log,
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def write_normalized_csv(path: Path, candidates: list[Candidate]) -> None:
    write_csv(path, [candidate.review_dict() for candidate in candidates], NORMALIZED_FIELDS)


def write_review_csv(path: Path, candidates: list[Candidate]) -> None:
    write_csv(path, [candidate.review_dict() for candidate in candidates], REVIEW_FIELDS)


def write_duplicates_csv(path: Path, rows: list[dict]) -> None:
    write_csv(path, rows, DUPLICATE_FIELDS)


def write_conflicts_csv(path: Path, rows: list[dict]) -> None:
    write_csv(path, rows, CONFLICT_FIELDS)


def write_source_metadata(path: Path, metadata: dict) -> None:
    path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")


def write_validation_json(path: Path, *, summary: dict, errors: list[str], warnings: list[str]) -> None:
    path.write_text(
        json.dumps({"summary": summary, "errors": errors, "warnings": warnings}, indent=2),
        encoding="utf-8",
    )


def write_sql(path: Path, records: list[PolicyRecord]) -> None:
    rows = []
    for record in records:
        data = record.db_dict()
        rows.append("  (" + ", ".join(_sql_value(field, data[field]) for field in DB_FIELDS) + ")")

    header = """-- Generated by frontier-policy-ingestion-v2 for AI Laws by State — Education AI Tracker.
-- REVIEW ONLY: this command never writes to Supabase.
-- Only NEW, validated records are included. Existing MultiState records are excluded so their
-- current official source and research provenance are not silently overwritten.
"""
    if not rows:
        path.write_text(header + "\n-- No NEW validated rows were eligible for SQL generation.\n", encoding="utf-8")
        return

    sql = f"""{header}
insert into public.policies
  ({', '.join(DB_FIELDS)})
values
{',\n'.join(rows)}
on conflict (state_code, policy_identifier, source_url)
do nothing;
"""
    path.write_text(sql, encoding="utf-8")


def summarize(candidates: list[Candidate], conflicts: list[dict]) -> dict:
    category_counter = Counter()
    for candidate in candidates:
        category_counter.update(candidate.categories)
    return {
        "source_row_count": len(candidates),
        "jurisdiction_count": len({c.state_code for c in candidates if c.state_code}),
        "source_categories": dict(sorted(Counter(c.raw.source_category for c in candidates).items())),
        "source_statuses": dict(sorted(Counter(c.raw.source_status for c in candidates).items())),
        "normalized_primary_categories": dict(sorted(Counter(c.category for c in candidates if c.category).items())),
        "normalized_all_categories": dict(sorted(category_counter.items())),
        "classifications": dict(sorted(Counter(c.classification for c in candidates).items())),
        "records_lacking_official_source_url": sum(1 for c in candidates if not c.source_url),
        "conflict_count": len(conflicts),
        "source_consistency_review_count": sum(1 for c in candidates if c.review_flags),
        "source_consistency_blocking_review_count": sum(
            1 for c in candidates if c.has_blocking_review_flags() and not c.is_reviewed_exclusion()
        ),
        "resolved_source_mismatch_exclude_count": sum(
            1 for c in candidates if c.review_disposition == "EXCLUDE_SOURCE_MISMATCH"
        ),
        "source_consistency_warning_count": sum(
            1 for c in candidates if c.review_flags and not c.has_blocking_review_flags()
        ),
        "bill_identity_review_count": sum(
            1 for c in candidates if any(flag.startswith("Bill identity mismatch:") for flag in c.review_flags)
        ),
        "education_scope_review_count": sum(
            1 for c in candidates if any(flag.startswith("Education-scope mismatch:") for flag in c.review_flags)
        ),
        "review_dispositions": dict(sorted(Counter(c.review_disposition for c in candidates).items())),
        "reviewed_exclude_count": sum(1 for c in candidates if c.is_reviewed_exclusion()),
        "reviewed_bill_identity_exclude_count": sum(
            1 for c in candidates if c.review_disposition == "EXCLUDE_BILL_IDENTITY_MISMATCH"
        ),
        "reviewed_non_education_scope_exclude_count": sum(
            1 for c in candidates if c.review_disposition == "EXCLUDE_NON_EDUCATION_SCOPE"
        ),
        "verified_include_count": sum(1 for c in candidates if c.review_disposition == "INCLUDE_VERIFIED"),
        "unresolved_review_count": sum(
            1
            for c in candidates
            if not c.is_reviewed_exclusion()
            and c.review_disposition != "INCLUDE_VERIFIED"
            and (c.classification in {"INVALID", "POSSIBLE_MATCH_REVIEW"})
        ),
        "dc_record_count": sum(1 for c in candidates if c.state_code == "DC"),
        "federal_review_only_count": sum(1 for c in candidates if c.raw.state_name == "United States (Federal)"),
    }


def write_report(
    path: Path,
    *,
    source_url: str,
    summary: dict,
    validation_errors: list[str],
    warnings: list[str],
    output_names: list[str],
) -> None:
    classifications = summary.get("classifications", {})
    lines = [
        "# AI Laws by State — Education AI Tracker ingestion report",
        "",
        f"- Research source: {source_url}",
        "- CLI command: `python -m app.cli ingest-ai-laws-education`",
        f"- Run mode: {summary.get('mode', 'unknown')}",
        f"- Existing-policy comparison source: {summary.get('existing_comparison_source', '')}",
        f"- Existing-policy comparison source kind: {summary.get('existing_comparison_source_kind', '')}",
        f"- Source rows extracted: {summary['source_row_count']}",
        f"- State/DC jurisdictions represented after jurisdiction normalization: {summary['jurisdiction_count']}",
        f"- NEW: {classifications.get('NEW', 0)}",
        f"- DUPLICATE_EXISTING: {classifications.get('DUPLICATE_EXISTING', 0)}",
        f"- POSSIBLE_MATCH_REVIEW: {classifications.get('POSSIBLE_MATCH_REVIEW', 0)}",
        f"- INVALID: {classifications.get('INVALID', 0)}",
        f"- Conflicts with existing records: {summary['conflict_count']}",
        f"- Source-consistency review flags: {summary.get('source_consistency_review_count', 0)}",
        f"- Blocking source-consistency reviews: {summary.get('source_consistency_blocking_review_count', 0)}",
        f"- Resolved source-mismatch exclusions: {summary.get('resolved_source_mismatch_exclude_count', 0)}",
        f"- Non-blocking source-consistency warnings: {summary.get('source_consistency_warning_count', 0)}",
        f"- Bill-identity review rows: {summary.get('bill_identity_review_count', 0)}",
        f"- Education-scope review rows: {summary.get('education_scope_review_count', 0)}",
        f"- Verified review includes: {summary.get('verified_include_count', 0)}",
        f"- Reviewed/excluded rows: {summary.get('reviewed_exclude_count', 0)}",
        f"- Unresolved review rows: {summary.get('unresolved_review_count', 0)}",
        f"- Records lacking official government source URLs: {summary['records_lacking_official_source_url']}",
        f"- DC records: {summary['dc_record_count']}",
        f"- Federal tracker rows kept review-only: {summary['federal_review_only_count']}",
        f"- Validation errors: {len(validation_errors)}",
        "- Production Supabase modified: NO",
        "- Frontend/backend changes made: NO",
        "- Frontend/backend compatibility: NOT ASSESSED in this archive because those source trees were not included",
        "",
        "## Source-declared counts",
        "",
    ]
    declared = summary.get("source_declared_counts", {})
    if declared:
        lines += [f"- {key}: {value}" for key, value in declared.items()]
    else:
        lines.append("- Not available in the supplied fixture/page markup")
    lines += ["", "## Source category counts", ""]
    lines += [f"- {key}: {value}" for key, value in summary["source_categories"].items()]
    lines += ["", "## Source status counts", ""]
    lines += [f"- {key}: {value}" for key, value in summary["source_statuses"].items()]
    lines += ["", "## Normalized AI Choice category counts", ""]
    lines += [f"- {key}: {value}" for key, value in summary["normalized_all_categories"].items()]
    lines += ["", "## Validation", ""]
    if validation_errors:
        lines += [f"- ERROR: {error}" for error in validation_errors]
    else:
        lines.append("- PASS: no blocking validation errors")
    if warnings:
        lines += ["", "## Warnings / review notes", ""]
        lines += [f"- {warning}" for warning in warnings]
    lines += ["", "## Generated files", ""]
    lines += [f"- `{name}`" for name in output_names]
    lines += [
        "",
        "## Load safety",
        "",
        "This command produces review artifacts and, only when validation fully passes, SQL for manual review.",
        "It never calls the Supabase loader or modifies production data.",
        "Existing MultiState matches are excluded from generated SQL to preserve their approved provenance.",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")

