from __future__ import annotations

import csv
import json
from collections import Counter
from pathlib import Path

from app.exporters import DB_FIELDS, _sql_value
from app.models import PolicyRecord
from app.sources.edchoice_school_choice import Candidate, DashboardRow, QUALIFYING_UNIVERSAL_VALUES

REVIEW_FIELDS = [
    "classification",
    "validation_result",
    "issues",
    "review_flags",
    "exclusion_reason",
    "source_state",
    "state_code",
    "program_type",
    "program_name",
    "dashboard_universal",
    "classification_source",
    "classification_source_url",
    "dashboard_enacted",
    "dashboard_launched",
    "program_url",
    "detail_title",
    "detail_truly_universal",
    "detail_universal_eligibility",
    "detail_universal_usage",
    "detail_universal_funding",
    "funding_mechanism",
    "governing_statute_text",
    "governing_statute_url",
    "policy_identifier",
    "title",
    "summary",
    "policy_type",
    "category",
    "categories",
    "status",
    "status_detail",
    "effective_date",
    "implementation_timeline",
    "source_url",
    "research_source_name",
    "research_source_url",
    "research_source_date",
    "status_as_of_date",
    "last_updated",
    "last_verified_at",
    "duplicate_existing_title",
    "duplicate_existing_source_url",
]

DUPLICATE_FIELDS = [
    "classification",
    "state_code",
    "program_name",
    "existing_title",
    "existing_source_url",
    "existing_research_source_name",
    "existing_research_source_url",
    "reason",
]

CONFLICT_FIELDS = [
    "state_code",
    "program_name",
    "field",
    "existing_value",
    "edchoice_value",
    "resolution",
]

CHANGE_FIELDS = [
    "change_type",
    "state_code",
    "program_name",
    "existing_title",
    "existing_source_url",
    "reason",
]


def write_csv(path: Path, rows: list[dict], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def write_raw_json(path: Path, rows: list[DashboardRow], detail_log: list[dict], source_date: str | None) -> None:
    payload = {
        "source_date": source_date,
        "rows": [row.raw_dict() for row in rows],
        "detail_fetches": detail_log,
    }
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def write_normalized_csv(path: Path, candidates: list[Candidate]) -> None:
    write_csv(path, [c.review_dict() for c in candidates], REVIEW_FIELDS)


def write_review_csv(path: Path, candidates: list[Candidate]) -> None:
    write_csv(path, [c.review_dict() for c in candidates], REVIEW_FIELDS)


def write_duplicates_csv(path: Path, rows: list[dict]) -> None:
    write_csv(path, rows, DUPLICATE_FIELDS)


def write_conflicts_csv(path: Path, rows: list[dict]) -> None:
    write_csv(path, rows, CONFLICT_FIELDS)


def write_changes_csv(path: Path, rows: list[dict]) -> None:
    write_csv(path, rows, CHANGE_FIELDS)


def write_source_metadata(path: Path, metadata: dict) -> None:
    path.write_text(json.dumps(metadata, indent=2, ensure_ascii=False), encoding="utf-8")


def write_validation_json(path: Path, *, summary: dict, errors: list[str], warnings: list[str]) -> None:
    path.write_text(
        json.dumps({"summary": summary, "errors": errors, "warnings": warnings}, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def write_sql(path: Path, records: list[PolicyRecord]) -> None:
    header = """-- Generated by frontier-policy-ingestion for EdChoice Universal School Choice.
-- REVIEW ONLY: this command never writes to Supabase.
-- Apply database/02_add_universal_school_choice_category.sql first on an existing v2 table.
-- Only NEW, validated records are included.
"""
    if not records:
        path.write_text(header + "\n-- No NEW validated rows were eligible for SQL generation.\n", encoding="utf-8")
        return

    rows = []
    for record in records:
        data = record.db_dict()
        rows.append("  (" + ", ".join(_sql_value(field, data[field]) for field in DB_FIELDS) + ")")

    sql = f"""{header}
insert into public.policies
  ({', '.join(DB_FIELDS)})
values
{',\n'.join(rows)}
on conflict (state_code, policy_identifier, source_url)
do nothing;
"""
    path.write_text(sql, encoding="utf-8")


def summarize(candidates: list[Candidate], conflicts: list[dict], changes: list[dict]) -> dict:
    classifications = Counter(c.classification for c in candidates)
    qualifying_values = {value.lower() for value in QUALIFYING_UNIVERSAL_VALUES}
    qualifying = [c for c in candidates if c.raw.universal.strip().lower() in qualifying_values]
    return {
        "raw_source_entries": len(candidates),
        "qualifying_universal_school_choice_entries": len(qualifying),
        "qualifying_full_entries": sum(1 for c in qualifying if c.raw.universal.strip().lower() == "full"),
        "qualifying_eligibility_entries": sum(1 for c in qualifying if c.raw.universal.strip().lower() == "eligibility"),
        "qualifying_state_count": len({c.state_code for c in qualifying if c.state_code}),
        "qualifying_states": sorted({c.raw.state_name for c in qualifying}),
        "classifications": dict(sorted(classifications.items())),
        "new_records_ready_for_sql": sum(1 for c in candidates if c.is_valid_for_db()),
        "records_lacking_official_source_url": sum(1 for c in qualifying if not c.source_url),
        "conflict_count": len(conflicts),
        "source_change_review_count": len(changes),
        "category_counts": dict(sorted(Counter(c.category for c in qualifying if c.category).items())),
        "status_counts": dict(sorted(Counter(c.status for c in qualifying if c.status).items())),
    }


def write_report(
    path: Path,
    *,
    source_url: str,
    summary: dict,
    validation_errors: list[str],
    warnings: list[str],
    output_names: list[str],
    mode: str,
) -> None:
    classifications = summary.get("classifications", {})
    lines = [
        "# EdChoice — Universal School Choice ingestion report",
        "",
        f"- Research source: {source_url}",
        "- CLI command: `python -m app.cli ingest-edchoice-universal-school-choice`",
        f"- Run mode: {mode}",
        f"- Extraction method: {summary.get('extraction_method') or 'not recorded'}",
        f"- Raw source entries: {summary['raw_source_entries']}",
        f"- Qualifying Universal School Choice entries: {summary['qualifying_universal_school_choice_entries']}",
        f"- Qualifying states: {', '.join(summary['qualifying_states']) or 'none'}",
        f"- NEW: {classifications.get('NEW', 0)}",
        f"- DUPLICATE_EXISTING: {classifications.get('DUPLICATE_EXISTING', 0)}",
        f"- POSSIBLE_MATCH_REVIEW: {classifications.get('POSSIBLE_MATCH_REVIEW', 0)}",
        f"- INVALID: {classifications.get('INVALID', 0)}",
        f"- EXCLUDED: {classifications.get('EXCLUDED', 0)}",
        f"- NEW records ready for SQL: {summary['new_records_ready_for_sql']}",
        f"- Missing official source URL: {summary['records_lacking_official_source_url']}",
        f"- Conflicts: {summary['conflict_count']}",
        f"- Source-change reviews: {summary['source_change_review_count']}",
        f"- Validation errors: {len(validation_errors)}",
        "- Production Supabase modified: NO",
        "- Chatbot/document RAG modified: NO",
        "",
        "## Classification rule",
        "",
        "Primary rule: rows whose EdChoice dashboard `Universal` value is `Full` or `Eligibility` are normalized to `Universal School Choice`.",
        "If the dashboard table is absent from server HTML, the first-party Universal School Choice page is used as a fallback: every program under Universal Eligibility qualifies; programs that also appear under Universal Options and Universal Funding for a Truly Universal state are classified as Full.",
        "Dashboard rows marked `N/A` or any other non-qualifying value are kept visible as EXCLUDED and are not policy-write candidates.",
        "",
        "## Date handling",
        "",
        "Enacted and launched years are retained as source facts but are not converted into `effective_date`.",
        "`effective_date` remains null unless a source explicitly provides one.",
        "",
        "## Validation",
        "",
    ]
    if validation_errors:
        lines += [f"- ERROR: {item}" for item in validation_errors]
    else:
        lines.append("- PASS: no blocking validation errors")
    if warnings:
        lines += ["", "## Warnings / review notes", ""] + [f"- {item}" for item in warnings]
    lines += ["", "## Generated files", ""] + [f"- `{name}`" for name in output_names]
    lines += [
        "",
        "## Load safety",
        "",
        "This command only creates review artifacts and SQL. It never calls the Supabase loader.",
        "Existing records are not overwritten, and source removals are surfaced for review rather than deleted.",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
