import csv
import json
from pathlib import Path

from app.models import PolicyRecord

DB_FIELDS = [
    "state_code",
    "state_name",
    "policy_identifier",
    "title",
    "summary",
    "policy_type",
    "category",
    "categories",
    "status",
    "status_detail",
    "effective_date",
    "implementation_timeline",
    "source_url",
    "research_source_name",
    "research_source_url",
    "research_source_date",
    "status_as_of_date",
    "last_updated",
    "last_verified_at",
]
REVIEW_FIELDS = DB_FIELDS


def write_csv(path: Path, rows: list[dict], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def write_review_csv(path: Path, records: list[PolicyRecord]) -> None:
    write_csv(path, [r.review_dict() for r in records], REVIEW_FIELDS)


def _db_csv_row(record: PolicyRecord) -> dict:
    row = record.db_dict()
    row["categories"] = json.dumps(row["categories"], ensure_ascii=False)
    return row


def write_db_csv(path: Path, records: list[PolicyRecord]) -> None:
    write_csv(path, [_db_csv_row(r) for r in records], DB_FIELDS)


def _sql_literal(value) -> str:
    if value is None or value == "":
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def _sql_array(values: list[str]) -> str:
    return "array[" + ", ".join(_sql_literal(v) for v in values) + "]::text[]"


def _sql_value(field: str, value) -> str:
    if field == "categories":
        return _sql_array(value)
    return _sql_literal(value)


def write_upsert_sql(path: Path, records: list[PolicyRecord]) -> None:
    rows = []
    for record in records:
        data = record.db_dict()
        rows.append("  (" + ", ".join(_sql_value(field, data[field]) for field in DB_FIELDS) + ")")

    update_fields = [
        field
        for field in DB_FIELDS
        if field not in {"state_code", "policy_identifier", "source_url"}
    ]
    update_sql = ",\n  ".join(f"{field} = excluded.{field}" for field in update_fields)

    sql = f"""-- Generated by frontier-policy-ingestion v2.
-- Review output/policies_review.csv before running this file.
-- MultiState status is preserved in status_detail; status is the stable UI/filter group.
-- Source snapshot date is retained as status_as_of_date/last_updated.

insert into public.policies
  ({', '.join(DB_FIELDS)})
values
{',\n'.join(rows)}
on conflict (state_code, policy_identifier, source_url)
do update set
  {update_sql};
"""
    path.write_text(sql, encoding="utf-8")


def write_validation_json(path: Path, errors: list[str], summary: dict) -> None:
    path.write_text(json.dumps({"summary": summary, "errors": errors}, indent=2), encoding="utf-8")


def write_source_metadata(path: Path, metadata: dict) -> None:
    path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")


def write_report(path: Path, source_url: str, source_date: str, summary: dict, errors: list[str]) -> None:
    lines = [
        "# Policy Ingestion Report",
        "",
        f"- Research source: {source_url}",
        f"- Source snapshot date: {source_date}",
        f"- Extracted named policy rows: {summary['record_count']}",
        f"- States represented by named policies: {summary['state_count']}",
        f"- Validation errors: {summary['error_count']}",
        "",
        "## Scope",
        "",
        "This adapter ingests every bill explicitly listed in the article's three Key Bills sections.",
        "The article also reports broader tracking totals (134 bills across 31 states), but it does not enumerate all of those bills on this page.",
        "The import therefore must not be presented as complete 31-state or 50-state coverage.",
        "",
        "## Status handling",
        "",
        "The detailed article status is retained in status_detail. The status column is the stable UI/filter grouping.",
        "The source snapshot date is preserved; this import does not claim that the status is current on the date the script is run.",
        "",
        "## Status groups",
        "",
    ]
    for key, value in summary["statuses"].items():
        lines.append(f"- {key}: {value}")
    lines += ["", "## Detailed source statuses", ""]
    for key, value in summary["status_details"].items():
        lines.append(f"- {key}: {value}")
    lines += ["", "## Primary category counts", ""]
    for key, value in summary["primary_categories"].items():
        lines.append(f"- {key}: {value}")
    lines += ["", "## All category assignments", ""]
    for key, value in summary["all_categories"].items():
        lines.append(f"- {key}: {value}")
    if errors:
        lines += ["", "## Validation errors", ""] + [f"- {e}" for e in errors]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
