-- AI Choice / AI Choice Map
-- Fresh-create schema (v2).
-- Run this when creating the policies table from scratch.
-- IMPORTANT: CREATE TABLE IF NOT EXISTS does not upgrade an existing v1 table.

create table if not exists public.policies (
  id bigint generated by default as identity primary key,

  -- Jurisdiction / identity
  state_code varchar(2) not null,
  state_name text not null,
  policy_identifier text not null,             -- e.g. SB 1227, AB 1159, A 9190
  title text not null,                         -- display title, e.g. Idaho SB 1227

  -- Policy content
  summary text not null,
  policy_type text not null,                   -- Bill, Law, Regulation, Guidance, Other

  -- category = primary category kept for simple UI/backward-compatible filtering.
  -- categories = all supported categories that materially apply to the policy.
  category text not null,
  categories text[] not null,

  -- status = stable high-level UI/filter status.
  -- status_detail = source-specific legislative/administrative status.
  status text not null,
  status_detail text not null,

  effective_date date null,
  implementation_timeline text null,

  -- Official government / legislative source shown to the visitor.
  source_url text not null,

  -- Research/discovery provenance (for example MultiState).
  research_source_name text null,
  research_source_url text null,
  research_source_date date null,

  -- Date through which the imported status is supported by the research source.
  status_as_of_date date not null,

  -- Public-facing "last updated" value retained for the existing API/UI.
  -- For the initial MultiState import this is the source snapshot date (2026-04-09),
  -- not the date the ingestion script happens to run.
  last_updated date not null,

  -- Set only when Frontier independently re-checks the official source.
  last_verified_at timestamptz null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint policies_state_code_format
    check (state_code ~ '^[A-Z]{2}$'),

  constraint policies_policy_type_check
    check (policy_type in ('Bill','Law','Regulation','Guidance','Other')),

  constraint policies_category_check
    check (category in ('AI Use','Student Privacy','Parental Consent','AI Literacy','School Procurement','Universal School Choice')),

  constraint policies_categories_nonempty_check
    check (cardinality(categories) > 0),

  constraint policies_categories_values_check
    check (
      categories <@ array[
        'AI Use',
        'Student Privacy',
        'Parental Consent',
        'AI Literacy',
        'School Procurement',
        'Universal School Choice'
      ]::text[]
    ),

  constraint policies_primary_category_in_categories_check
    check (category = any(categories)),

  constraint policies_status_check
    check (status in ('Pending','Enacted','Active','Inactive','Unknown')),

  constraint policies_unique_source
    unique (state_code, policy_identifier, source_url)
);

create index if not exists idx_policies_state_code
  on public.policies (state_code);

create index if not exists idx_policies_category
  on public.policies (category);

create index if not exists idx_policies_categories_gin
  on public.policies using gin (categories);

create index if not exists idx_policies_status
  on public.policies (status);

create index if not exists idx_policies_policy_type
  on public.policies (policy_type);

create index if not exists idx_policies_state_category_status
  on public.policies (state_code, category, status);

create index if not exists idx_policies_status_as_of_date
  on public.policies (status_as_of_date desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_policies_set_updated_at on public.policies;
create trigger trg_policies_set_updated_at
before update on public.policies
for each row execute function public.set_updated_at();

-- Browser access stays closed; Express uses the Supabase server-side secret/service-role key.
alter table public.policies enable row level security;
